networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./access.log:/var/log/traefik/access.log
    labels:
      traefik.enable: true
      traefik.http.routers.traefik_https.rule: Host(`proxy.{{DOMAIN}}`)
      traefik.http.routers.traefik_https.entrypoints: websecure
      traefik.http.routers.traefik_https.tls: true
      traefik.http.routers.traefik_https.tls.certResolver: production #staging
      traefik.http.routers.traefik_https.service: api@internal 
      traefik.http.middlewares.basic-auth-traefik.basicauth.users: {{USER}}:{{PASSWORD}}
      traefik.http.routers.traefik_https.middlewares: basic-auth-traefik
    networks:
      - proxy
    restart: always