name: Check Bash Syntax
on: [push]
jobs:
    Check-Syntax:
        runs-on: ubuntu-latest
        steps:
            - run: bash -n /github/workspace/clean-server.sh
            - run: bash -n /github/workspace/link-autodeploy.sh