name: Check Bash Syntax
on: [push]
jobs:
    Check-Syntax:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: ls -la
            - run: bash -n ./clean-server.sh
            - run: bash -n ./link-autodeploy.sh